moneyadviceservice/mas-cms-client

README.md
lib/mas/cms/connection.rb
lib/mas/cms/entity/category.rb
mas-cms-client.gemspec
spec/factories/category.rb
spec/mas/cms/attribute_builder_spec.rb
spec/mas/cms/config_spec.rb
spec/mas/cms/entity/entity_spec.rb
spec/mas/cms/entity/home_page_spec.rb
spec/mas/cms/entity/video_spec.rb

**Target Process ticket**: _supports_ [TP#8612](https://moneyadviceservice.tpondemand.com/entity/8612)
**Summary**
This work was done to support an [on-going work](https://github.com/moneyadviceservice/frontend/compare/8612_pensions-webchat?expand=1) for displaying the TPAS(The Pension Advice Service) pension banner in the _Pensions and Retirement_ category. 
**Checklist**
+ [x] Tests passed.
+ [x] Rubocop is passing for this PR (or any other lint like JShint).
+ [x] Commit history reviewed (clear commit messages).

[DEV APPROVED] - 8612 Improve Categories API on MAS CMS gem

---

Gemfile
README.md
lib/mas/cms.rb
lib/mas/cms/entity/article_preview.rb
spec/factories/category.rb
spec/mas/cms/config_spec.rb
spec/mas/cms/entity/article_preview_spec.rb
spec/mas/cms/entity/home_page_spec.rb
spec/mas/cms/entity/video_spec.rb

https://moneyadviceservice.tpondemand.com/entity/8664
On the CMS, when the editors are changing one article, they have the possibility to preview the article. This preview feature is implemented on the site [here](https://github.com/moneyadviceservice/frontend/blob/master/app/controllers/articles_preview_controller.rb#L5)
Today the gem don't support previewing articles hence this PR. This PR includes the client communication when the editors are previewing the article before publishing it.
This is to support the work of replacing the old code with the gem.
This is the old code:
https://github.com/moneyadviceservice/frontend/blob/master/app/controllers/articles_preview_controller.rb#L5
https://github.com/moneyadviceservice/frontend/blob/master/lib/core/interactor/article_previewer.rb …

[DEV APPROVED] 8664 Add article preview client

---

lib/mas/cms/client/version.rb
lib/mas/cms/connection.rb
mas-cms-client.gemspec
spec/mas/cms/connection_spec.rb

[TP 8806](https://moneyadviceservice.tpondemand.com/entity/8806-mas-cms-client-does-not-handle)
Categories do not return `404` status when missing instead choosing to return a `200` status and a body of `null`
While this is valid JSON most parses have some trouble dealing with this so quirks mode must be enabled example:
```Ruby
irb(main):007:0> JSON.parse('null', quirks_mode:true)
=> nil
irb(main):008:0> JSON.parse('null')
JSON::ParserError: 784: unexpected token at 'null'
from /Users/phil/.gem/ruby/2.3.3/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
from /Users/phil/.gem/ruby/2.3.3/gems/json-1.8.6/lib/json/common.rb:155:in `parse'
from (irb):8
from /Users/phil/.rubies/ruby-2.3.3/bin/irb:11:in `<main>'
```
This PR enables the quirks mode in the faraday middleware and raises the …

8803 fix issue where null response could not be processed

---

README.md
lib/mas/cms.rb
lib/mas/cms/client/version.rb
lib/mas/cms/entity/home_page_preview.rb
spec/mas/cms/entity/home_page_preview_spec.rb

This PR is for [TP ticket 8812](https://moneyadviceservice.tpondemand.com/entity/8812-add-home-page-preview-page-type)
The Home Page Preview page type does not currently exist in mas-cms-client. This PR adds it.
We want to replace the legacy implementation of retrieving the Home Page in Frontend with the mas-cms-client gem, as described in [TP 8666](https://moneyadviceservice.tpondemand.com/entity/8666-use-mas-cms-client-gem-on).
In order to achieve this we also need to be able to replace the implementation for Home Page Preview.

[DEV APPROVED] 8812 Add Home Page Preview as page type

---

README.md
lib/mas/cms.rb
lib/mas/cms/client/version.rb
lib/mas/cms/entity/article_preview.rb
lib/mas/cms/entity/home_page_preview.rb
lib/mas/cms/entity/video.rb
lib/mas/cms/entity/video_preview.rb
lib/mas/cms/preview.rb
spec/mas/cms/entity/article_preview_spec.rb
spec/mas/cms/entity/home_page_preview_spec.rb
spec/mas/cms/entity/video_preview_spec.rb
spec/mas/cms/entity/video_spec.rb
spec/support/shared_examples/preview.rb

**Target Process ticket**
[TP 8830](https://moneyadviceservice.tpondemand.com/entity/8830-changes-to-gem-to-enable-use)
**Summary**
In order to support [TP 8669](https://moneyadviceservice.tpondemand.com/entity/8669-use-mas-cms-client-gem-on) a `VideoPreview` page type is needed, this PR adds it.
Additional notes:
* Whilst replacing the legacy code with the call to `Mas::Cms::Video`, it was discovered that attributes were not being set correctly on the returned `Video`. Changing that class to inherit from `Page` means that it now uses the `AttributeBuilder`, which resolves the issue.
* I've extracted the duplicate code from `ArticlePreview`, `HomePagePreview` and `VideoPreview` into a `Preview` module. Happy to revert this if it's adding unnecessary complication.

[DEV APPROVED] 8830 Add VideoPreview and fix issue with missing Video attributes

---

lib/mas/cms/client/version.rb
lib/mas/cms/entity/footer.rb
lib/mas/cms/entity/web_chat.rb
spec/mas/cms/entity/footer_spec.rb
spec/mas/cms/entity/web_chat_spec.rb

[TP #8395](https://moneyadviceservice.tpondemand.com/entity/8935-add-web-chat-to-footer-entity)
The footer entity does not currently include the web chat entity that is required by frontend.
This PR adds the `WebChat` entity and the accompanying method in `Footer`

[DEV APPROVED] 8395 Added Webchat entity

---

mas-cms-client.gemspec

Since I start to add mas-cms-client gem to the [Fincap]() the bundler complain:
```
Bundler could not find compatible versions for gem "activemodel":
In snapshot (Gemfile.lock):
activemodel (= 5.0.6)
In Gemfile:
mas-cms-client was resolved to 1.1.0, which depends on
activemodel (>= 4.2.7, ~> 4.2)
rails (~> 5.0.6) was resolved to 5.0.6, which depends on
activemodel (= 5.0.6)
web-console (>= 3.3.0) was resolved to 3.5.1, which depends on
activemodel (>= 5.0)
```
The reason is the gem *officially* does not support Rails 5. Changing the gemspec allow us to use the gem on Rails 5 applications.

[DEV APPROVED] Add compatibility to Rails 5

---

README.md
lib/mas/cms.rb
lib/mas/cms/entity/document.rb
lib/mas/cms/entity/footer.rb
lib/mas/cms/resource.rb
spec/mas/cms/entity/document_spec.rb
spec/mas/cms/entity/video_spec.rb
spec/mas/cms/resource_spec.rb

[TP-card](https://moneyadviceservice.tpondemand.com/entity/9015-add-documentall-to-mas-cms-client)
This is the client request to the CMS API work that was done on https://github.com/moneyadviceservice/cms/pull/403
The document resource on CMS uses root nodes on the response,
and this commit add the possibility for you to extend the resource
adding the 'root_node' method to your class.
Refer to lib/mas/cms/entity/document.rb for an example

[DEV APPROVED] 9015 - Add Document.all request

---

test.sh

*No TP cards*.
There was no rubocop check on this test.sh gem. Add one so it can run on our CI.

[DEV APPROVED] Add rubocop check to test.sh

---

lib/mas/cms/client/version.rb
lib/mas/cms/connection.rb
lib/mas/cms/resource.rb
spec/mas/cms/connection_spec.rb
spec/mas/cms/resource_spec.rb

[TP task](https://moneyadviceservice.tpondemand.com/entity/9038-mas-cms-client-should-send-the) from [TP card](https://moneyadviceservice.tpondemand.com/entity/8773-evhub-resultssearch-page-insights)
Before this implementation, we were requesting all documents to the CMS.
This would be a problem when new page types like articles enter on CMS because then the evidence hub could contain undesired page types on evidence summaries.
So this task cover to add the request all "Insight documents" to the CMS on the mas-cms-client gem.
So now the gem has support to pass parameters when you're requesting a collection like `/api/en/documents.json` then is possible to pass params on the request like
`/api/en/documents.json?document_type=Insight`

[DEV APPROVED] 9038 - Allow params in Resource.all requests

---

Jenkinsfile

This change add a post pipeline step to clear the Jenkins workspace. This prevents issues occurring with stale code in subsequent jobs.

[DEV APPROVED] Add post-step to clear workspace after jenkins job

---

lib/mas/cms.rb
lib/mas/cms/client/version.rb
lib/mas/cms/entity/article.rb
lib/mas/cms/entity/block.rb
lib/mas/cms/repository/cms/attribute_builder.rb
spec/fixtures/cms/article-components.json
spec/mas/cms/attribute_builder_spec.rb
spec/mas/cms/entity/article_spec.rb

[]()
The Mas::Cms::Article entity does not have a way to access other blocks from response.
The current implementation ignores the other blocks that are not content.
So this PR address this issue by making sure that other blocks which are NOT content
can be accessed from article entity via #extra_blocks accessor.
```
[1] pry(main)> article = Mas::Cms::Article.find('some-article')
[2] pry(main)> article.non_content_blocks
=> [#<Mas::Cms::Block:0x007fded37dc378 @content="<p>/hero-sample.jpg</p>\n", @identifier="component_hero_image">,
#<Mas::Cms::Block:0x007fded37dc080
@content=
"<p><a href=\"/financial+capability+strategy.pdf\">UK Strategy</a>\n<a href=\"/detailed-strategy.pdf\">UK Detailed Strategy</a>\n<a href=\"/key-statistics.pdf\">Key statistics on Financial Capability</a>\n<a …
```

Add extra blocks attribute to article pages

---

lib/mas/cms/connection.rb
spec/mas/cms/connection_spec.rb

Every time that there is an error on the client that is requesting the CMS *which is not a problem on the CMS* an weird error is raised:
This error above happens because there are some cases which the exception does not have a response. Like SSL errors, timeouts, so checking if there is a response makes the exception go through and raise the Mas::Cms::Errors::ClientError passing the right exception and the right message.

Fix client error exception when exception does not have a response

---

lib/mas/cms/client/version.rb

This version fixes the handle of exceptions when the request raises an error without response. See #26  for more details.

Bump version to 1.12.1

---

README.md
lib/mas/cms/client/version.rb
lib/mas/cms/entity/article.rb

[TP 9202](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9202)
The requirement is for a Fincap page which shows summaries of all the Thematic Reviews. This pr amends the gem which interacts with the cms to enable getting all Articles. Changes are also required to fin_cap and the cms.
A `root_node` method needs to be added to Article

Get all Articles from CMS

---

lib/mas/cms/client/version.rb
lib/mas/cms/entity/article.rb
lib/mas/cms/repository/cms/attribute_builder.rb
spec/factories/category.rb
spec/mas/cms/config_spec.rb
spec/mas/cms/entity/article_spec.rb
spec/mas/cms/entity/home_page_spec.rb
spec/mas/cms/entity/video_spec.rb

[TP 9202](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9202)
The requirement is for a Fincap page which shows summaries of all the Thematic Reviews. This pr amends the gem which interacts with the cms.
[Related fin_cap pr](https://github.com/moneyadviceservice/fin_cap/pull/143)
- Add the full_path attribute to the Article class. This attribute is used in fin_cap views for displaying links to specific articles, e.g. thematic reviews
- Fix rubocop offenses

Add full_path attribute to Article

---

README.md
lib/mas/cms.rb
lib/mas/cms/client/version.rb
lib/mas/cms/entity/article.rb
lib/mas/cms/entity/evidence_summary_preview.rb
spec/mas/cms/entity/evidence_summary_preview_spec.rb

[TP 9186](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9186)
Fincap website editors need to preview their changes/additions to Fincap Evidence Summaries (Insights, Evaluations and Reviews),  once a draft version has been entered into the cms, before the document is published.
Since insights, evaluations and reviews all inherit from EvidenceSummary, we only need to add 1 new class, EvidenceSummaryPreview which makes use of the Preview class. This work is in conjunction with work being done on Fincap.
This work also includes some code changes in line with our rubocop standards.

Changes for fincap preview feature

---

lib/mas/cms/entity/article.rb

[TP 9283](https://moneyadviceservice.tpondemand.com/restui/board.aspx#page=board/5481321774608038243&appConfig=eyJhY2lkIjoiNjRGM0FCMDY3RUQ5MDREM0RGNDZGOUM0REZENUZBMzIifQ==&searchPopup=userstory/9283)
A number of FinCap pages need to show related news articles. Related news articles are those that have the same tags as the current page.
Currently, the cms and this gem do not include the tags associated with an article in the response. This pr adds the capability for tags to be accessed when passed through from the cms to fincap

9283 latest news component for Fincap

---

bin/console
lib/mas/cms/client/version.rb
lib/mas/cms/connection.rb
spec/mas/cms/connection_spec.rb

This makes better to figure it out what is wrong when requesting to CMS raises error like SSL problems instead of having debugging the raw connection from Faraday.

Add message when client receive errors

---

README.md
lib/mas/cms.rb
lib/mas/cms/client/version.rb
lib/mas/cms/entity/news_preview.rb
spec/mas/cms/entity/news_preview_spec.rb

This pr continues the work for [TP 9186](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5580782241563718174&appConfig=eyJhY2lkIjoiRTQ4MDEyNENDOUYxRDU4RDg0RTEyRjNCODBEN0VBMUYifQ==&searchPopup=userstory/9186)
Fincap website editors need to preview their changes/additions to Fincap News pages and the Latest News page  once a draft version has been entered into the cms, before the document is published.

[DEV APPROVED] - Enable previewing news type pages for fincap

---

lib/mas/cms/entity/article.rb
lib/mas/cms/entity/category.rb
lib/mas/cms/entity/clump.rb
lib/mas/cms/entity/home_page.rb
lib/mas/cms/entity/other.rb
lib/mas/cms/entity/static_page.rb
lib/mas/cms/entity/video.rb
lib/mas/cms/repository/cms/attribute_builder.rb
spec/mas/cms/attribute_builder_spec.rb
spec/mas/cms/entity/article_spec.rb
spec/mas/cms/entity/category_spec.rb
spec/mas/cms/entity/clump_spec.rb
spec/mas/cms/entity/corporate_spec.rb
spec/mas/cms/entity/static_page_spec.rb
spec/mas/cms/entity/video_spec.rb

[TP Card](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=userstory/9569)
- In order for the meta information to be displayed correctly both description and meta_title have to be assigned. 
- To future-proof the feature I have added the meta_title to all entities having a `description`
- Tested ok for all entities types requested:
```
Homepage
Review
Insight
Evaluation
Lifestage
News
```

[DEV APPROVED] - [9569] Add meta_title attribute to entities

---

Dangerfile
Dockerfile
Gemfile
Jenkinsfile
docker-compose.yml
lib/mas/cms/repository/cms/attribute_builder.rb
mas-cms-client.gemspec
spec/mas/cms/attribute_builder_spec.rb
test.sh

The Jenkins config is outdated in this repo. Some updates to improve test and build.
- Update the Jenkins pipelines to use docker-compose
- Set the Rubocop test fail-level to `error` until all offences resolved
- Add Danger gem

Update Jenkins to use docker-compose

---

lib/mas/cms/entity/clump.rb
spec/mas/cms/entity/clump_spec.rb

[TP card](https://moneyadviceservice.tpondemand.com/entity/8217-make-the-cms-clumps-api-url)
A route has been added to the CMS that exposes clumps via the path
/api/:locale/clumps, bringing the URL structure of clumps in line with
other API resources. Remove the api_prefix method override so that
CMS clients make use of the new route.
Version increment and release to follow.

[DEV APPROVED] Remove API prefix override in Clump entity

---

Dockerfile
Jenkinsfile

To improve Jenkins build times and general efficiency we can now pull a standard base image from our private Azure container registry. This removes the requirement to maintain explicit an Dockerfile across all our repos.
N.B The Dockerfile and docker-compose.yml are still available in the repo if there's additonal specific dependencies / requirements.

Use base image from private container registry
